HTML select options for BCP-47 languages. 
Ready for Cloud Speech-to-Text API. 
Language tags follow the HTTP/1.1 specification, section 3.10.

<select>
    <option value="en-US" selected>English</option>
    <option value="" disabled>---</option>
    <option value="af-ZA">Afrikaans</option>
    <option value="sq-AL">Albanian</option>
    <option value="am-ET">Amharic</option>
    <option value="ar-DZ">Arabic (Algeria)</option>
    <option value="ar-BH">Arabic (Bahrain)</option>
    <option value="ar-EG">Arabic (Egypt)</option>
    <option value="ar-IQ">Arabic (Iraq)</option>
    <option value="ar-IL">Arabic (Israel)</option>
    <option value="ar-JO">Arabic (Jordan)</option>
    <option value="ar-KW">Arabic (Kuwait)</option>
    <option value="ar-LB">Arabic (Lebanon)</option>
    <option value="ar-MA">Arabic (Morocco)</option>
    <option value="ar-OM">Arabic (Oman)</option>
    <option value="ar-QA">Arabic (Qatar)</option>
    <option value="ar-SA">Arabic (Saudi Arabia)</option>
    <option value="ar-PS">Arabic (State of Palestine)</option>
    <option value="ar-TN">Arabic (Tunisia)</option>
    <option value="ar-AE">Arabic (United Arab Emirates)</option>
    <option value="ar-YE">Arabic (Yemen)</option>
    <option value="hy-AM">Armenian</option>
    <option value="az-AZ">Azerbaijani</option>
    <option value="eu-ES">Basque</option>
    <option value="bn-BD">Bengali, Bangla</option>
    <option value="bg-BG">Bulgarian</option>
    <option value="my-MM">Burmese</option>
    <option value="ca-ES">Catalan</option>
    <option value="zh">Chinese (Mandarin)</option>
    <option value="hr-HR">Croatian</option>
    <option value="cs-CZ">Czech</option>
    <option value="da-DK">Danish</option>
    <option value="nl-NL">Dutch</option>
    <option value="et-EE">Estonian</option>
    <option value="fi-FI">Finnish</option>
    <option value="fr-FR">French</option>
    <option value="gl-ES">Galician</option>
    <option value="ka-GE">Georgian</option>
    <option value="de-DE">German</option>
    <option value="el-GR">Greek</option>
    <option value="gu-IN">Gujarati</option>
    <option value="iw-IL">Hebrew</option>
    <option value="hi-IN">Hindi</option>
    <option value="hu-HU">Hungarian</option>
    <option value="is-IS">Icelandic</option>
    <option value="id-ID">Indonesian</option>
    <option value="it-IT">Italian</option>
    <option value="ja-JP">Japanese</option>
    <option value="jv-ID">Javanese</option>
    <option value="kn-IN">Kannada</option>
    <option value="km-KH">Khmer (Cambodia)</option>
    <option value="ko-KR">Korean</option>
    <option value="lo-LA">Lao</option>
    <option value="lv-LV">Latvian, Lettish</option>
    <option value="lt-LT">Lithuanian</option>
    <option value="mk-MK">Macedonian</option>
    <option value="ms-MY">Malay</option>
    <option value="ml-IN">Malayalam</option>
    <option value="mr-IN">Marathi</option>
    <option value="mn-MN">Mongolian</option>
    <option value="ne-NP">Nepali</option>
    <option value="no-NO">Norwegian</option>
    <option value="fa-IR">Persian</option>
    <option value="pl-PL">Polish</option>
    <option value="pt-PT">Portuguese</option>
    <option value="pa-Guru-IN">Punjabi</option>
    <option value="ro-RO">Romanian</option>
    <option value="ru-RU">Russian</option>
    <option value="sr-RS">Serbian</option>
    <option value="si-LK">Sinhala</option>
    <option value="sk-SK">Slovak</option>
    <option value="sl-SI">Slovenian</option>
    <option value="es-AR">Spanish (Argentina) </option>
    <option value="es-BO">Spanish (Bolivia) </option>
    <option value="es-CL">Spanish (Chile) </option>
    <option value="es-CO">Spanish (Colombia) </option>
    <option value="es-CR">Spanish (Costa Rica) </option>
    <option value="es-DO">Spanish (Dominican Republic) </option>
    <option value="es-EC">Spanish (Ecuador) </option>
    <option value="es-EV">Spanish (El Salvador) </option>
    <option value="es-GT">Spanish (Guatemala) </option>
    <option value="es-HN">Spanish (Honduras) </option>
    <option value="es-MX">Spanish (Mexico)</option>
    <option value="es-NI">Spanish (Nicaragua) </option>
    <option value="es-PA">Spanish (Panama) </option>
    <option value="es-PY">Spanish (Paraguay) </option>
    <option value="es-PE">Spanish (Peru) </option>
    <option value="es-PR">Spanish (Puerto Rico) </option>
    <option value="es-ES">Spanish (Spain) </option>
    <option value="es-UY">Spanish (Uruguay) </option>
    <option value="es-VE">Spanish (Venezuela) </option>
    <option value="su-ID">Sundanese</option>
    <option value="sw-KE">Swahili</option>
    <option value="sv-SE">Swedish</option>
    <option value="fil-PH">Tagalog</option>
    <option value="ta-IN">Tamil</option>
    <option value="te-IN">Telugu</option>
    <option value="th-TH">Thai</option>
    <option value="tr-TR">Turkish</option>
    <option value="uk-UA">Ukrainian</option>
    <option value="ur-IN">Urdu</option>
    <option value="uz-UZ">Uzbek</option>
    <option value="vi-VN">Vietnamese</option>
    <option value="zu-ZA">Zulu</option>
</select>
